### ISSUE TITLE
Enable use of DEIMOS bias frames with imaging mode header

### ISSUE THREAD

**Issue by abostroem** [pypeit/PypeIt#1150]
When pypeIt_setup is run on a bias frame with MOSMODE=DIRECT the following is output and the file is skipped:

```[WARNING] :: Found frames with invalid amp.
[WARNING] :: Found frames with invalid mode.
[WARNING] :: The following frames have configurations that cannot be reduced by PypeIt and will be removed from the metadata table (pypeit file):
  d0828_0018.fits```

It would be nice to be able to use these biases

**Comment by kbwestfall** [comment]
Thanks for submitting the issue!  After talking with Keck staff, they pointed me to this:

https://www2.keck.hawaii.edu/inst/deimos/deimos_ccd_mosaic.html

When MOSMODE=Direct, the biases aren't taken in a format that can be used with MOSMODE=Spectral data.  Sorry for the confusion.

Closing this issue because we will need to continue to reject images with MOSMODE=Direct in pypeit.
