### ISSUE TITLE
Identify not functional

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#1165]
So this is another minor issue. When trying to use the manual identification method from the pypeit file an error occurs because of the nonlinear_counts variable (I believe this has been deprecated) at line 953 in core/arc.py:

    good = np.invert(np.isnan(twid)) & (twid > 0.0) & (twid < fwhm_max/2.35) & (tcent > 0.0) \
                & (tcent < xrng[-1]) & **(tampl_true < nonlinear_counts)**  \
                & (np.abs(tcent-pixt) < fwhm*0.75)

Since nonlinear_counts always has nonetype this will always cause an error.

**Comment by profxj** [comment]
@rcooke-ast -- do you know if this was corrected?

**Comment by rcooke-ast** [comment]
I have no idea... Sorry - I didn't notice the Issue! Looking at the code, it seems the problem would have been with line 233 of `identify.py`, and I can't see why this would be a problem any more. I would consider it solved, but pypeit is broken for me at the moment (due to an astropy upgrade) so I can't check right now...

**Comment by rcooke-ast** [comment]
Just checked, and this issue seems to be addressed.
