### ISSUE TITLE
Refactor fit_func, etc. with desiutils.funcfits

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#125]
Includes a nice dict wrapper, additional tests, etc.
See:
https://github.com/desihub/desiutil/blob/master/py/desiutil/funcfits.py

Would require desiutils as a new dependency.

**Comment by rcooke-ast** [comment]
I like what you've done to the set of routines, but I can't say that I'm too keen on adding another dependency.... particularly because it's pulling from another DR pipeline, and also because this code originated in PYPIT. Personally, I would prefer to avoid the additional dependency, and include your modifications into the PYPIT arutils script.

(The PYPIT and desiutils routines would then evolve independently).

**Comment by profxj** [comment]
We have moved more towards `pydl`
