### ISSUE TITLE
Trouble overwriting spectrograph parameters?

### ISSUE THREAD

**Issue by prappleizer** [pypeit/PypeIt#1366]
Hi, 

I am trying to reduce Palomar DBSP / red data, and it appears that the instrument's specific configs want to use reidentify using a template spectrum, but no template spectrum exists for my grating and dichroic combo. 

I would like to try to run the reduction using another method (e.g., holy-grail) and indeed, it seems the way to MAKE a new template would be via this method. But despite adding 

```
[calibrations]
  [[wavelengths]]
     method = holy-grail
``` 

to my pypeit file, the setting does not appear to be overwritten, and I still get an error 

`pypeit.pypmsgs.PypeItError: Your grating 1200/7100 needs a template spectrum for the red arm of DBSP.` 

I am sure I am missing something simple here, but would appreciate any guidance on how I am supposed to run the pipeline with the other non-template-dependent methods (even if they don't work, I'd like to try).

**Comment by finagle29** [comment]
That error message is happening because the Palomar DBSP-specific code doesn't check that the wavelength calibration method is `reid_arxiv` before throwing an error for no template spectrum (my bad!). For an immediate fix, you'll need to comment out/edit the offending lines in the DBSP code.

To find the file to edit, just run `python -c "from pypeit.spectrographs import p200_dbsp; print(p200_dbsp.__file__)"`. Then you'll need to replace line 594 ` msgs.error("Your grating " + grating + " needs a template spectrum for the red arm of DBSP.")` with `pass`, so that the error doesn't occur.

**Comment by prappleizer** [comment]
Ah, thank you for the quick response! I will try that fix out.
