### ISSUE TITLE
Wrong Geocentric Coordinates for Telescopes

### ISSUE THREAD

**Issue by joaquinhernandezg** [pypeit/PypeIt#1462]
The latitude for the several telescopes in telescopes.py has a wrong value. It produces a shift in heliocentric wavelength calibration, for example. GTC has a longitude of 17.877, it should be negative. Same for Keck, Magellan, VLT, and others.

**Comment by profxj** [comment]
@rcooke-ast -- do you agree with this?

**Comment by rcooke-ast** [comment]
Interesting... a good find... We have always defined longitudes in `telescopes.py` with west representing positive longitudes.

The problem appears to be that Astropy's [EarthLocation](https://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html#astropy.coordinates.EarthLocation) defines East as positive longitudes.

I suspect this bug was introduced when we moved to astropy (quite some time ago) instead of doing the calculation internally. Probably, we should use the inbuilt telescope locations provided by astropy. I suspect they are more likely to be updated, and kept consistent going forward.

Thanks @joaquinhernandezg for spotting and reporting the bug!

**Comment by rcooke-ast** [comment]
I'll do some additional checks, because we originally checked all of the values against `x_keckhelio` so I'm reluctant to change it unless we can confidently confirm that it is a bug... I'll keep looking into it, and submit a hotfix if needed...

**Comment by profxj** [comment]
Thanks!

**Comment by rcooke-ast** [comment]
OK - I've cross-checked this against other codes, and it seems we have a bug. I'll patch it now.

**Comment by rcooke-ast** [comment]
Fixed by PR #1464
