### ISSUE TITLE
Cannot install PypeIt for some reason

### ISSUE THREAD

**Issue by JoshuaPovick** [pypeit/PypeIt#1475]
I'm trying to install PypeIt on my laptop and everything I have tried does not seem to work. I would prefer to use pip. I have tried pip3 and also the conda installation instructions. Other people that I know, who have installed PypeIt on a similar machine, did not run into any issues. Any help would be much appreciated. 

Here are the specs of my laptop:
<img width="592" alt="macbook_specs" src="https://user-images.githubusercontent.com/36514540/193100048-33c0cbd3-9909-47f4-bfdf-0844b75b8532.png">

I currently have Python 3.8.5 installed

Here is the error message at the end:
<img width="570" alt="error_message" src="https://user-images.githubusercontent.com/36514540/193100139-b3b3dd70-b5cf-4b91-a28d-f7a53e6c96ae.png">

Full output printed in terminal from running `pip install "pypeit[pyqt5]"`:
[fullterm_error.txt](https://github.com/pypeit/PypeIt/files/9677719/fullterm_error.txt)

**Comment by kbwestfall** [comment]
You're getting a lot of `SetuptoolsDeprecationWarning`s that I don't understand, but I'm wondering if the real issue is:

`error: command '/usr/bin/gcc' failed with exit code 1`

Do you have gcc installed?  You may need to update XCode and/or install gcc.  If you've never used it before, Homebrew (https://brew.sh/) makes installing things like gcc pretty easy.  Once you have homebrew installed, installing gcc is something like `brew install gcc`.

**Comment by JoshuaPovick** [comment]
Thank you so much @kbwestfall! 

I didn't have XCode or gcc. Apparently when you have two laptops it's easy to assume you have done something on one, but in reality it was a different computer. I feel smart now.

**Comment by kbwestfall** [comment]
Haha, no worries.  Glad this was an easy fix.  Not all installation issues are ...  Thanks for reporting that you solved the problem and for closing the issue!
