### ISSUE TITLE
Wrong numpy attributes

### ISSUE THREAD

**Issue by RuiningZHAO** [pypeit/PypeIt#1523]
In pypeit/core/trace.py

line 117: `tedges = np.zeros(flux.shape, dtype=np.float)` raises `AttributeError: module 'numpy' has no attribute 'float'`

line 125: `edge_img = np.zeros(sobel_sig.shape, dtype=np.int)` raises `AttributeError: module 'numpy' has no attribute 'int'`

In pypeit/core/pydl.py

line 431: `self.outmask = np.zeros(xpos.shape, dtype=np.bool)` raises `AttributeError: module 'numpy' has no attribute 'bool'`

There are more...

pypeit==1.11.0
numpy==1.24.0

**Comment by lboogaard** [comment]
Running into the same issue on a fresh install of `pypeit`. The reason is that the use of `np.int` and `np.float`, etc., is deprecated since `numpy=1.20.0` (https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) and removed as of `numpy=1.24.0` (https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations). Downgrading numpy to `1.23.0` works as a workaround.

**Comment by kbwestfall** [comment]
Apologies. We're getting a number of users experiencing the same issue. This should be fixed in a new version of PypeIt (1.12.0), which should hopefully be ready soon (~week-ish timescale). In the meantime, the best solution is to revert to numpy==1.23, as you've done.
