### ISSUE TITLE
How do I find my object? Please improve documention! 

### ISSUE THREAD

**Issue by jasonmold** [pypeit/PypeIt#1549]
I am struggling to understand what this software does. With lot of effort and supervision, I managed to go through the initial steps: install, set up, reduce science spectra, reduce standard star, fluxing. I do not like that it is such a black box and I had no control over what was happening. Nonetheless, I thought the worst was over until I tried to understand where my source is. Pypeit found 9 different objects, is my object among them? how do I find it? I have been reading the documention for three days but I am still lost. Please improve the user documentation or post a detailed step-by-step tutorial on YouTube, this is too hard to understand and very very frustrating.

**Comment by kbwestfall** [comment]
Hi @jasonmold .  I encourage you to join the PypeIt Users Slack.  The invitation link can be found on the front page of our docs.  Specifically, see here:

https://pypeit.readthedocs.io/en/release/#community

Once you do so, please hop on the #guidelines channel, read the Google doc bookmarked to that channel, and then post your question(s) in a relevant channel.  We continue to try to improve the docs, but interaction over the Users Slack provides a more immediate way for us to support users.

To find your object of interest, I'd encourage you to use the `pypeit_show_2dspec` script.  See here:

https://pypeit.readthedocs.io/en/release/out_spec2D.html

This will show the calibrated 2D spectral images and overlay the object traces, with their PypeIt identifiers.  Once you've found the relevant object identifier, you can find the extracted spectrum in the `spec1d` file(s).  See here:

https://pypeit.readthedocs.io/en/release/out_spec1D.html

For a step-by-step cookbook, see:

https://pypeit.readthedocs.io/en/release/cookbook.html

There are also instrument-specific tutorials here:

https://pypeit.readthedocs.io/en/release/tutorials/tutorials.html

Even if your instrument isn't among those with an existing tutorial, looking at those docs will provide some generally applicable guidance, in addition to the general cookbook.

If you have additional, specific advice on how we can improve the documentation, we welcome the input!

**Comment by jasonmold** [comment]
Sorry this isn't very useful. I already followed the steps you suggested, which are also those generically described in the online documentation. However, this is missing the main point: pypeit_show_2dspec shows many different traces associated with an obscure SPAT identifier. How do I understand which one is my target? Presumably the target is the one at the center but in my case there are 3-4 traces in that area. Moreover, I have four exposures of the same target and the SPAT ID changes between different exposures. It is really hard and time-consuming to understand where the target lies in each exposure.

**Comment by kbwestfall** [comment]
Again, please join the Users Slack.  Troubleshooting like this isn't efficient here, and you'll be drawing from a larger pool of people that have used the code and can provide advice.

If the code is finding more objects than it should, you may need to change the object finding parameters.  See here:

https://pypeit.readthedocs.io/en/release/object_finding.html

and here:

https://pypeit.readthedocs.io/en/release/pypeit_par.html#findobjpar

PypeIt can only match detected objects to those you intended to observe for specific instruments with mask design information.  If you're not using one of those instruments, you either have to do the matching yourself or you can try using the 2D coadding scripts to combine the data so that you only get one spectrum per detected object.

**Comment by profxj** [comment]
@jasonmold - what improvements to the docs would you suggest here?
