### ISSUE TITLE
KCRM datacube WCS is rotated by 180 degrees

### ISSUE THREAD

**Issue by ddobie** [pypeit/PypeIt#1677]
KCRM datacubes appear to have a 180 degree rotation relative to KCWI datacubes. The below screenshot shows KCRM (left) and KCWI (right) cube slices from observations of a standard star with locked WCS.

![image](https://github.com/pypeit/PypeIt/assets/25451772/dca3630c-5a82-4328-ad01-6a7df2c2aa90)

From a brief investigation the KCWI datacube has the correct WCS (other than #1674) and it is the KCRM data that is rotated.

**Comment by rcooke-ast** [comment]
Thanks @ddobie - As discussed on the Users Slack, this is because KCRM has an extra mirror (so the image is flipped relative to KCWI). This issue is resolved in the branch `kcrm_Sep23`, and will be merged into the development branch shortly after a few more quality controls. You are one of the first to be reducing KCRM data!
