### ISSUE TITLE
Consider using numba for just-in-time compilation speedup

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#23]
con: Developed and provided by Anaconda
pro: super-easy otherwise and can be _huge_ speedup

**Comment by rcooke-ast** [comment]
I now propose that we consider using numba instead of cython (see also, Issue #198). There's simply no way around this with the triangles algorithm in arclines - we can get a factor ~100 speedup.

numba is developed by the conda team, and comes as standard in the conda install. So, although it's a "dependency", users will automatically have it installed (if they use conda, as recommended).

What say you @profxj?  I think we'll need to use numba or cython, and I'm now in favour of removing cython code and porting it to numba.

**Comment by rcooke-ast** [comment]
Check out the latest PR in arclines, for an example.

**Comment by rcooke-ast** [comment]
numba is now in the code for wavelength calibration. I dare say we may see it even more in the future, now that it is a dependency.
