### ISSUE TITLE
specifying the number of calibs in pypit file

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#417]
Hi @kbwestfall, 

I love what you have done with the parsets,  the documentation, and the new format for the pypit files. 
One piece of feedback.   I think we should strive for the simplest interface. 

At present, we have to explicitly specify the number of calibration frames of each type in the pypit file under the calibrations. Example is below. I feel strongly that this should be simplified.  You have a file list below specifying exactly the files that the user wants to use. There is no reason to have to explicitly 
specify it in the parset, as the information is already in the pypit file in file list. If a user wants to use fewer files, they can comment out the relevant file lines. By having to specify the filenames twice, are
the pre-amble of the PYPIT file longer for no reason since the information is already there. Previously we did not have to specify these frame numbers explicitly, and I see no reason to do so now. 

calibrations]
    [[biasframe]]
        number = 2
    [[pixelflatframe]]
        number = 3
    [[traceframe]]
        number = 3

Thanks,
Joe

**Comment by rcooke-ast** [comment]
I think it’s good to have the option to specify this in the pypeit file, but it shouldn’t be mandatory (we should have some sensible defaults).

I can think of cases where commenting out filenames won’t work. For example,  sometimes I bracket each science exposure with an arc frame when observing with hires, so if I want to reduce a whole night of hires data with one pypeit file, I want to specify that only one arc should be used (or even sometimes, I want to combine two arcs). So I think flexibility will be a good thing.

**Comment by profxj** [comment]
We definitely want this functionality.  The key issue is the defaults.
I was tempted to set them all to 0, but the code generally needs
an arc to make any progress [for optical].    Still, maybe 0 is best.

**Comment by jhennawi** [comment]
So why not set the default to 1 and not require it in the pypit file. The other point I should add, is that this could be simply addressed with another key in the pypit file list, which is group #. 

The pypit_setup script can group the arcs and science frames together as it sees best, and the user can feel free to change these groupings as they see fit. In that way, we would not need to specify a number of arcs, biases, etc.

**Comment by kbwestfall** [comment]
A few comments/questions:
 - Is there currently documentation on how PypeIt does the matching?
 - What happens if the number of frames of a given type is 0.  Does it just use all of them?
 - How do I tell from the output which frames were used to calibrate each science frame and/or science spectrum?
 - It's straight-forward to change the default number for a given frame type.  The default for all `FrameGroupPar` objects is `number=0`, see [here](https://github.com/PYPIT/PYPIT/blob/e24c536b2ea72b2d3afbbc73f360c72d6ab8db4f/pypit/par/pypitpar.py#L135).  But they can be changed for a specific frame group, as done [here](https://github.com/PYPIT/PYPIT/blob/e24c536b2ea72b2d3afbbc73f360c72d6ab8db4f/pypit/par/pypitpar.py#L1617) for the arc frames.  There are also instrument-specific defaults using the `default_pypit_par` function for each spectrograph, like [this](https://github.com/PYPIT/PYPIT/blob/e24c536b2ea72b2d3afbbc73f360c72d6ab8db4f/pypit/spectrographs/shane_kast.py#L197) for example.  The only reason you would set the number in the pypit file is if you want it to be different from the spectrograph defaults.
 - What would people think of having multiple pypit files per set of observations?  I.e., instead of having a single file where pypit does the matching each time it's run based on the data in the pypit file, we have a sorting script that creates one pypit file for each group of associated calibration and science frames.  Then once you're happy with how frames are grouped, you can run pypit in a "batch" mode that uses all the pypit files in a directory to reduce your data.  We could give the pypit files names like `shane_kast_n1.0.pypit`,  `shane_kast_n1.1.pypit`, etc.  This way we separate the frame matching (`pypit_setup`) from the execution of the data reduction (`run_pypit`).

**Comment by profxj** [comment]
Excellent questions.  Here are some quick (not so informative) answers:

1.  No docs that I know of
2.  Not sure
3.  You'd have to inspect the fitstbl that is output to disk, if you mean after the fact
4.  For the last one, I worry that could get excessive when it is needed and most of the time will not be needed.

**Comment by jhennawi** [comment]
Hi All, 

I think @kbwestfall addressed my concern that the parameter is not actually required. 

-- Let me suggest again that we simply create a group index in the pypit files next to each frame for this kind of thing. I realize it adds one extra column, but it then solves the issue of the user changing which frames are used to calibrate which images. I agree with @kbwestfall that a separate pypit file
is one plausible solution, but in the case where the user wants to use all the afternoon calibs (biases, flats, etc.) but just wants to use arcs taken on the sky (because of flexure or whatever) then this provides an easy solution without all the files and the extra script. 

-- As for @kbwestfall question about "how do we know which calibs were used" my suggestion would be that we simply change the naming convention of the master files to include the group number, and the file used (or the first file used) to create the master file. The group would usually be zero, and the filename in the name of the master makes it clear which file the calibration is based on. '

Joe

**Comment by profxj** [comment]
closing
