### ISSUE TITLE
Fix readthedocs

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#447]

**Comment by profxj** [comment]
Stil shows the old docs..

**Comment by kbwestfall** [comment]
I was thinking about this.  Is there any info on what python environment is available with readthedocs tries to build the documentation?  It might be that the build fails because of the python code that's called to construct the parameter set documentation fails.  It would be worth commenting out that code from the `make build` command just as a test to see if the docs are otherwise updated.

**Comment by profxj** [comment]
Fixed.
