### ISSUE TITLE
pypeit_setup grabs wrong disperser header cards for LRIS red

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#466]

**Comment by kbwestfall** [comment]
I assume this is the same as #449 ?

**Comment by jhennawi** [comment]
Yes indeed. Shall I close this one then?

**Comment by kbwestfall** [comment]
Yeah, I'll do it now.  I'm actually working on this at the moment for LRISr.  I started thinking it would just be for this instrument to help get it up and running again on the dev suite.  But X and I both found for different reason that the whole frame typing functionality has been broken for most instruments since we moved to the `Spectrograph` class.  We never really migrated the full `settings` functionality over for this.  I imagine this is what I'm likely to spend most/all of tomorrow on; i.e., trying to get the frame typing/checking back up and running.
