### ISSUE TITLE
problem with NIRSPEC frame matching

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#556]
The setup script is barfing for NIRSPEC. I replaced the keck_nirspec file with the one in the nirspec_new branch, but that did not fix it. 

I'm going to let this PR clear without this test, but it would be appreciated if it could be fixed. 

Thanks,
Joe

**Comment by kbwestfall** [comment]
I've kludged this for the moment.  I don't think the problem was in the frame matching, but in the frame typing.  Based on the pypeit file [here](https://github.com/pypeit/PypeIt-development-suite/blob/master/pypeit_files/keck_nirspec_nirspec1.pypeit), there aren't actually any "arc" frames in the NIRSPEC dev suite data, just a science exposure that should be treated as sky.  So the code was faulting because it couldn't find an arc frame.

The kludge I have in place allows the code to treat science frames as arc frames, but we need a better long-term solution for this.  We've talked about how to do that, and it's on my plate to start implementing it.  We should leave this issue open until that's done.
