### ISSUE TITLE
Dark vs. Overscan subtraction for near-IR

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#704]
Presently some near-IR instruments do an 'overscan' subtraction (X-Shooter)
while others don't (GNIRS, MOSFIRE).  I presume this is a kludge of sorts and that 
the proper solution would be to subtract a dark image.

If we agree, implement this.

If not, discuss why.

**Comment by jhennawi** [comment]
Hawaii2 detectors do not have overscan regions. So for that reason, you always need to subtract off a dark in principle. Since for science frames we difference image using the same exposure time, there is no need to subtract a dark because the b/g image has your bias, and all that good stuff in it. 

For processing calibrations, like flats, generally dark subtraction is necessary and will significantly improve results, like order tracing. We do not process arcs in the NIR, so I don't think there is a need to do this for arcs. At our request, Percy Gomez implemented a script to take darks in between flats with NIRES. This is already implemented for X-shooter. These darks are ideally taken during the same sequence i.e, lamp on lamp off, so that you get the persistence out of there. For MOSFIRE I'm not sure what they do. 

If anyone wants to reduce NIR data without differencing, which is the case for the current FIREHOSE pipeline, then generally speaking you need darks. Whether or not you can reduce NIR data without differencing depends very much on the quality of the detector. There are good Hawaii-2s and bad Hawaii-2s. I have not done the comparison for FIRE, but definitely with NIRES the results were way better when we difference imaged, notwithstanding the root-2 increase in noise. 

PypeIt does not currently have the ability to subtract darks from calibration images, or a Dark class. I think there is a dark image type but not sure how it is used. Probably not at all. This should be easy enough to implement with the "bg_frame" etc. index structure that we created.

**Comment by profxj** [comment]
Gone.  Darks are still an issue.
