### ISSUE TITLE
Edgetrace fails with cryptic error message

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#821]
The following pypeit file crashes with a cryptic error message. The issue is the edge_thresh=100.0 parameter. When edge_thresh is adjusted to the default of 20.0, the slits trace just fine. My issue
is that tuning edge_thresh for an instrument/setup is often a game of trial and error, but there is no QA
to visualize how this ought to be changed. 

Another minor issue is that all of the edgetrace QA is flipped from the pypeit convention of spectral direction vertical, and it would be appreciated if these images could be transposed before displayed to be consistent with the convention that we adopt for viewing images with ginga. 

To reproduce the error, run 

 pypeit_trace_edges -f gemini_gmos_south_ham_R400_860.pypeit

on the attached pypeit file. 

[gemini_gmos_south_ham_R400_860_std.pypeit.txt](https://github.com/pypeit/PypeIt/files/4114192/gemini_gmos_south_ham_R400_860_std.pypeit.txt)

**Comment by kbwestfall** [comment]
@jhennawi The issue was that there are no detected slit edges in the images.  (I'm actually not sure how this wasn't failing when using `edge_thresh=20`, as well.)  I put in a hook into `pypeit.core.trace.identify_traces` that makes sure there are detected edges before continuing.  The code then proceeds to add a left and right edge at the edge of each detector.  I made the change in the current `deimos_merge3` branch (PR #817 ).

I'll close this and add a new issue about the QA plot orientation.
