### ISSUE TITLE
Consolidate fitting routines

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#824]
There are a number of fitting routines scattered throughout the code (e.g., `iterfit`, `func_fit`, `robust_polyfit`, `robust_polyfit_djs`, etc).  Some of them are old and may not be used, some are preferred but the unpreferred versions are still used, and some seem (without digging to deeply) to be doing very similar if not effectively identical things.  We need to figure out which ones we use, which ones we use but should replace with other existing functions, which ones we should consolidate into single functions, and which ones we can delete.  And then for the ones we're left with, it would be good if they had distinct names that gave an immediate indication of what they do.

**Comment by jhennawi** [comment]
Hi Kyle, 
robust_polyfit_djs should replace robust_polyfit everywhere, but robust_polyfit is used in wavelengths only. It should be replaced and deprecated, but we have not done this yet. Iterfit is something totally different, a wrapper for the bspline class. func_fit is used for fitting Gaussians, and I think is called by robust_polyfit_djs

**Comment by kbwestfall** [comment]
Okay, thanks for the explanation.  Is there an intended difference between `utils.bspline_profile` and `pydl.iterfit`?

I'm harping on this because of a recent benchmark test I did.  In a run of just the calibrations for all eight DEIMOS detectors, it shows us constantly spamming `numpy.polynomial.legval` and `pypeit.utils.gauss_3deg`.  Each individual call is quick, but, e.g., in my test run it called `pypeit.utils.gauss_3deg` more than 100 *million* times.  There may be significant gains to be made by cleaning this up (like using `numpy.polynomial.legendre.legvander` and making sure we're always passing the relevant vectors to `pypeit.utils.gauss_3deg`).

**Comment by jhennawi** [comment]
So utils.bspline_profile is similar but more general than iterfit. One fits a bspline iteratively with the option to pass in an arbitrary profile for another dimension, the other (iterfit) fits a bspline modulated by a polynomial  profile function. In principle they should deliver identical results when the the profile function is set to be unity everywhere, but in practice they differ slightly (is my recollection). Unifying these into one algorithm would require digging into the guts of these codes which was not so trivial to port. It is easy to convince yourself that that your changes are resulting in identical results without testing all the usage cases (i.e. using the n-d polymoial fitting or profile fitting options). 

The profile basis being fed to these codes for flat fielding and sky-subtraction are being evaluated from pydl, i.e. pydl.flegendre. I suspect that it would be faster to use native numpy/scipy functions for this, since those are heavily optimized. 

Trying to make the bspline itself fully native python while maintaining the same functionality would require a professional programmer to do the port. The python bspline is crapp compared to what we have here, which is why the previous sky-subtraction was so unreliable. 

Joe

**Comment by profxj** [comment]
In progress in `wvcalib_refactor`.

Will need more help.

**Comment by profxj** [comment]
Now in PR #929

**Comment by profxj** [comment]
@kbwestfall -- good now?
