### ISSUE TITLE
Add an illumflat class

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#883]
Yes, yet another frametype.

This will be required for LRISb, eventually..

**Comment by jhennawi** [comment]
The current image selection logic in calibrations.get_flats is incorrect. We are using the traceflat for the pixelflat, which only works because in the dev suite for all impacted setups traceflat and pixelflat are not the same frame.  We need to distinguish between pixelflat and illumflat as image types and run the flat field code multiple times depending on what was passed, and then correctly assing the mspixelflat and msillumflat masters. The appropriate images should then be stored in the data container.

**Comment by profxj** [comment]
Even worse, I believe the `trace` will be used to generate a `pixelflat` and apply it
in cases where the user is only trying to apply an `illumflat` correction, e.g. MOSFIRE.

For now, I recommend that if you do not with to apply a pixelflat that you avoid flat-fielding altogether, i.e.

```
[calibrations]
  [[flatfield]]
    method=skip
```

This requires PR #891 to work.

**Comment by profxj** [comment]
added
