### ISSUE TITLE
JOSS review: Installation

### ISSUE THREAD

**Issue by astrom-tom** [pypeit/PypeIt#993]
Review of paper : [https://github.com/openjournals/joss-reviews/issues/2308](url)

Here is the one about installation: 

I could install it with the git clone section of the installation page. Although, I got an error:

```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from extension_helpers import get_extensions
ModuleNotFoundError: No module named 'extension_helpers'
```

After installing it manually, the python setup.py develop --user worked. This package should be added to the setup.py of the package so it is installed automatically. The pip install from pypi crashed.

**Comment by csnap001** [comment]
I had this issue as well, but found that the package 'extension_helpers' comes with python3. Once I switched my default python distribution to python3 I was able install without issue. Not sure if there would be problems with trying to install this package into a python2 distribution?

**Comment by astrom-tom** [comment]
My main point is that the package dependencies should be in the setup.py so there are installed when you install pypeit. For the moment  you are using the find_packages from setuptools. It seems it does not find some of the packages. Since your list of dependencies seems to be well defined, I would just write it down directly in the setup.py.

**Comment by kbwestfall** [comment]
Hi @astrom-tom .  

For `extension-helpers`, I think this was a typo in the requirements file.  This is now fixed, although weirdly both `pip3 install extension_helpers` and `pip3 install extension-helpers` works for me.

I'm not sure what you mean about `find_packages`, though.  This method finds the packages within pypeit itself.  I.e.:
```
$ cd PypeIt
$ python3
Python 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import find_packages
>>> find_packages()
['pypeit', 'pypeit.core', 'pypeit.images', 'pypeit.tests', 'pypeit.bspline', 'pypeit.scripts', 'pypeit.display', 'pypeit.spectrographs', 'pypeit.par', 'pypeit.core.gui', 'pypeit.core.wavecal']
```
 Do you instead mean the `install_requires` keyword for `setuptools.setup`?

We previously had the dependencies listed by the `install_requires` keyword.  See the `setup.py` file.  It's been a while, but I think we removed this because we didn't want users to unknowingly alter their current environment when they installed pypeit.  We instead moved the requirements file into the `pypeit` subdirectory and then use it to check that the dependencies are met; see `pypeit/check_requirements.py`.  It may seem round-about, but this way users know for sure that they're altering their packages when they install the dependencies instead of having `pip` or `setup.py` do it without their permission.  I'm interested to know what you think and if you have a specific recommendation for how to restructure this.

**Comment by profxj** [comment]
This Issue is related to JOSS review: openjournals/joss-reviews#2308

**Comment by astrom-tom** [comment]
Ok, once again sorry for the delay. It seems that now the installation works without problem! I will close this ticket.
